[project]
channels = ["conda-forge"]
description = "git@github.com:isce-framework/sweets.git"
name = "sweets"
platforms = ["linux-64", "osx-arm64"]
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/isce-framework/sweets"
repository = "https://github.com/isce-framework/sweets"

[tasks]
test = "pytest"
install = { depends-on = "pre-commit_install"}
pre-commit_install = "pre-commit install"

[dependencies]
cartopy = "*"
compass = "*"
distributed = "*"
dolphin = "*"
geopandas = "*"
opera-utils = ">0.1.1"
rioxarray = "*"

[pypi-dependencies]
sweets = { path = ".", editable = true}

[feature.dev]
dependencies = { pytest = ">=8.3.5,<9", pre_commit = "*", mypy = "*" }

[environments.default]
features = ["dev"]
